### health test
GET http://localhost:9500/health

#############################################################################
### endpoint for registering an admin
POST http://localhost:9500/api/register/admin
Content-Type: application/json

{
    "FirstName": "Jeff",
    "LastName": "Ndegwa",
    "Email": "example@gmail.com",
    "Password": "pass404",
    "NationalID": "12345678",
    "County": "Nyeri",
    "Residence": "Skuta",
    "PhoneNumber": "0712345678",
    "Gender": "Male",
    "DateOfBirth": "3/31/2000",
    "PhotoURL": "example.photo.url",
    "Role": "Admin"
}

### login as admin
POST http://localhost:9500/api/login/admin
Content-Type: application/json

{
    "Email": "ndegwajeff4103t@gmail.com",
    "Password": "pass404"
}

### get admin details by id
GET http://localhost:9500/api/admin/3

### update login details
PUT http://localhost:9500/api/admin/update/6
Content-Type: application/json

{
    "Email": "Kajiado34@gmail.com"
}

### get all admins
GET http://localhost:9500/api/admins

### delete an admin
DELETE http://localhost:9500/api/admin/delete/3

#############################################################################
### registering a user
POST http://localhost:9500/api/register/user
Content-Type: application/json

{
    "FirstName": "Steven",
    "LastName": "Jobs",
    "Email": "stevenjobs@gmail.com",
    "Password": "pass404",
    "NationalID": "12345678",
    "County": "Nyeri",
    "Residence": "Skuta",
    "PhoneNumber": "0712345678",
    "Occupation": "farmer",
    "Gender": "Male",
    "DateOfBirth": "3/31/2000",
    "PhotoURL": "example.photo.url",
    "Role": "User"

}

### login user 
POST http://localhost:9500/api/login/user
Content-Type: application/json

{
    "Email": "ndegwajeff41erGTY03ght@gmail.com",
    "Password": "pass404"
}

### get a user by its id
GET http://localhost:9500/api/user/4

### get all users
GET http://localhost:9500/api/users

### update user details
PUT http://localhost:9500/api/user/update/1
Content-Type: application/json

{
    "County": "Mombasa"
}

### delete a user
DELETE http://localhost:9500/api/user/delete/2

#############################################################################
### create a report
POST http://localhost:9500/api/createreport/1
Content-Type: application/json

{
    "Location": "Kiambu",
    "Type": "Domestic Violence",
    "Description": "I think my neighbour is going to kill his wife",
    "NoiseLevel": "high",
    "SourceOfNoise": "neighbour's house",
    "DurationOfNoise": "from 8pm to now",
    "SupportingDocuments": "example.photourl"
}

### get all reports
GET http://localhost:9500/api/reports

### get speficific reports from specific users
GET http://localhost:9500/api/report/1

### get one post
GET http://localhost:9500/api/onereport/2

### updating a record
PUT http://localhost:9500/api/updatereport/2
Content-Type: application/json

{
    "Type": "music"
}

### delete a report
DELETE http://localhost:9500/api/deletereport/2

#############################################################################
### create a feedback
POST http://localhost:9500/api/createfeedback/1
Content-Type: application/json

{
    "UserID": 1,
    "Message": "We are Workng on your request"
}

### get all feedbacks
GET http://localhost:9500/api/feedbacks

### get feedback for a certain user
GET http://localhost:9500/api/feedback/1

### update a feedback
PUT http://localhost:9500/api/updatefeedback/1
Content-Type: application/json

{
    "Message": "Updating feedback 1"
}

### delete a feedback
DELETE http://localhost:9500/api/deletefeedback/1

#############################################################################
### create a notification
POST http://localhost:9500/api/createnotification/1
Content-Type: application/json

{
    "Type": "Criminal Activity",
    "Status": "Investigating",
    "Description": " Criminals suspected to have broken down a local business in your area’If you hear anything please let us know. Investigations ongoing. "
}

### get all notifications
GET http://localhost:9500/api/notifications

### get one notification
GET http://localhost:9500/api/onenotification/1

### update a notification
PUT http://localhost:9500/api/updatenotification/1003
Content-Type: application/json

{
    "Status": "Solved"
}

### delete a notification
DELETE http://localhost:9500/api/deletenotification/2


#############################################################################
### create a Email
POST http://localhost:9500/api/createEmail/1
Content-Type: application/json

{
    "UserID": 1,
    "Subject": "Noise Pollution",
    "Email": "A domestic violence incident has been reported in your area. Please stay vigilant as authorities are en route to the location"
}

### get all Emails
GET http://localhost:9500/api/Emails

### get one Email
GET http://localhost:9500/api/oneEmail/6

### update a Email
PUT http://localhost:9500/api/updateEmail/6
Content-Type: application/json

{
    "Subject": "solved"
}

### delete a Email
DELETE http://localhost:9500/api/deleteEmail/6